live_config_reload = true

[colors.bright]
black = "#6c566a"
cyan = "#8fbcbb"
green = "#a5abb6"
white = "#eceff4"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[cursor.style]
blinking = "Never"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "monospace"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "linkhandler"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[[hints.enabled]]
action = "Copy"
post_processing = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "L"
mods = "Control|Shift"

[[hints.enabled]]
action = "Copy"
post_processing = false
regex = "([0-9]{2}[0-9]*)"

[hints.enabled.binding]
key = "N"
mods = "Control|Shift"

[[hints.enabled]]
action = "Copy"
post_processing = false
regex = '([0-9a-f]{12,128})|([[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3})'

[hints.enabled.binding]
key = "I"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 10000

[window]
decorations = "Full"
opacity = 0.87

[window.padding]
x = 2
y = 1
