'$schema' = "https://starship.rs/config-schema.json"

# Inserts a blank line between shell prompts
add_newline = false
# format = ' ${custom.upds}'
format = '$directory($git_branch$git_state$git_status$status)$character'
right_format = """"""

[character]
format = '\$ '

[git_branch]
format = '[$branch(:$remote_branch)]($style) '
style = 'bold purple'

[git_status]
format = '[$all_status$ahead_behind]($style) '

[directory]
truncation_length = 4
style = "bold lavender"

[cmd_duration]
min_time = 500

[status]
format = '($status)'
disabled = false

# [custom.upds]
# command = 'cat ~/.cache/updates' # shows output of command
# when = '[ "$(cat ~/.cache/updates)" -gt 0 ]'
# symbol = 'ðŸ“¦'
# format = '$output$symbol '
