'$schema' = "https://starship.rs/config-schema.json"

# Inserts a blank line between shell prompts
add_newline = false
# format = ' ${custom.upds}'
format = '$directory$status$character'
right_format = '$all'

[directory]
truncation_length = 4
style = "bold lavender"

[status]
format = '$status '
disabled = false

[character]
format = '\$ '

[cmd_duration]
format = ' [$duration]($style) '
min_time = 500
style = 'yellow'

[git_branch]
format = '[$branch]($style)'
style = 'bold purple'
[git_status]
disabled = true
format = '( [$all_status$ahead_behind]($style))'
ahead = 'â†‘'
behind = 'â†“'
diverged = 'â†•'

[jobs]
symbol = '*'

[battery]
disabled = true
[c]
disabled = true
[python]
disabled = true
[golang]
disabled = true
[lua]
disabled = true
[nodejs]
disabled = true
[dotnet]
disabled = true

# [custom.upds]
# command = 'cat ~/.cache/updates' # shows output of command
# when = '[ "$(cat ~/.cache/updates)" -gt 0 ]'
# symbol = 'ðŸ“¦'
# format = '$output$symbol '
