'$schema' = "https://starship.rs/config-schema.json"

# Inserts a blank line between shell prompts
add_newline = false
format = ' [\[$username@$hostname\]](bg:#000000) $all'
right_format = """$status"""

[character]
format = ' [‚ùØ](bold bright-yellow) '

[username]
style_root = "bold red"
style_user = "bold purple"
format = "[$user]($style bg:#000000)"
show_always = true
disabled = false

[hostname]
ssh_only = false
style = "bold cyan bg:#000000"
format = "[$hostname]($style)"

[directory]
truncation_length = 4
style = "bold lavender"

[cmd_duration]
min_time = 500

[status]
format = '($status)'
disabled = false
